
import * as fs from 'fs';
import * as path from 'path';

const LOCAL_DB_BASE = path.resolve('data/local_db');
const OUTPUT_FILE = path.resolve('data/generated_communities.ts');

async function main() {
    console.log("🚀 Syncing Local DB to Frontend...");

    const communities: any[] = [];
    let count = 0;

    if (!fs.existsSync(LOCAL_DB_BASE)) {
        console.error("❌ Local DB not found!");
        return;
    }

    const cities = fs.readdirSync(LOCAL_DB_BASE);
    for (const city of cities) {
        if (city.startsWith('.')) continue;
        const districts = fs.readdirSync(path.join(LOCAL_DB_BASE, city));

        for (const district of districts) {
            if (district.startsWith('.')) continue;
            const villages = fs.readdirSync(path.join(LOCAL_DB_BASE, city, district));

            for (const village of villages) {
                if (village.startsWith('.')) continue;

                const villagePath = path.join(LOCAL_DB_BASE, city, district, village);

                // Read 6 channel files
                let wiki: any = {};
                try { wiki = JSON.parse(fs.readFileSync(path.join(villagePath, 'wiki.json'), 'utf8')); } catch (e) { }

                let culture = [];
                try { culture = JSON.parse(fs.readFileSync(path.join(villagePath, 'culture.json'), 'utf8')); } catch (e) { }

                let travel = [];
                try { travel = JSON.parse(fs.readFileSync(path.join(villagePath, 'travel.json'), 'utf8')); } catch (e) { }

                let events = [];
                try { events = JSON.parse(fs.readFileSync(path.join(villagePath, 'events.json'), 'utf8')); } catch (e) { }

                let projects = [];
                try { projects = JSON.parse(fs.readFileSync(path.join(villagePath, 'projects.json'), 'utf8')); } catch (e) { }

                let care = [];
                try { care = JSON.parse(fs.readFileSync(path.join(villagePath, 'care.json'), 'utf8')); } catch (e) { }

                // Construct PublicCommunity Object
                const commId = `${city}_${district}_${village}`;

                // Map 'wiki' population/features to top level if needed by some UI components, 
                // but mostly keep it in 'wiki' object as per new schema.

                const community = {
                    id: commId,
                    name: village,
                    city: city,
                    district: district,
                    description: wiki.introduction || "暫無介紹",
                    tags: wiki.features || [],
                    location: [24.8 + (Math.random() * 0.1), 121.0 + (Math.random() * 0.1)], // Mock location if not real

                    // Embedded Channels - CLEARED AS PER USER REQUEST (Allow manual entry only)
                    wiki: wiki,
                    cultureHeritages: [], // culture,
                    travelSpots: [], // travel,
                    events: [], // events,
                    projects: [], // projects,
                    careActions: [], // care,

                    // Legacy/Root Fields for compatibility
                    chief: wiki.chief?.name,
                    population: wiki.population?.toString(), // Ensure string if UI expects string
                    communityBuildings: [],
                    boundary: []
                };

                communities.push(community);
                count++;
            }
        }
    }

    const fileContent = `// Auto-generated by scripts/sync_to_frontend.ts
// Do not edit manually. Edit data/local_db JSONs instead.

export const GENERATED_COMMUNITIES = ${JSON.stringify(communities, null, 2)};
`;

    fs.writeFileSync(OUTPUT_FILE, fileContent);
    console.log(`✅ Synced ${count} communities to ${OUTPUT_FILE}`);
}

main().catch(console.error);
